[ 입찰 거래 시스템 api 구현 ]
wecode-bootcamp-korea/48-2nd-F_Kiiler-backend pull request #11
Opened 2023-08-29 02:21 UTC by Junjiii

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성

경매 시스템 구현 목표 
1) 판매입찰
2) 구매입찰
3) 거래채결 

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
1) 판매입찰/ 구매입찰
controller 에서 (sellerId or buyerId /productId /size /price) 4가지 파라미터를 req.body로 받는다.
service 에서 (productId/ size) 를 통해 bidProductsize 의 id 를 찾아온다. 
찾아온 id 와 price 를 통해서 
(판매라면 구매입찰 대기 중인 상품을 찾아서 품목의 id 를 가져온다.)
(구매라면 판애입찰 대기 중인 상품을 찾아서 품목의 id 를 가져온다.)
if 문 을 통해  
품목의 Id 가 없다면 ? -> 판매/구매 입찰 대기 중인 주문서를 작성한다. 
<거래채결>
 품목의 id 가 있다면? -> 
판매/구매 입찰에 status를  입찰완료로 주문서를 작성한다. 
찾아온 id 의 status 를 "입찰완료" 라고 수정한다.
찾아온 파라미터를 사용해 order 주문서를 작성한다.  

<br />

## :: 테스트 결과 이미지
1. Server가 잘 동작하는지 확인할 수 있는 Terminal 캡쳐 이미지
2. Postman(Client Tool)을 이용한 API 테스트 결과 이미지
3. 작성한 Test Code가 잘 통과했는지 확인할 수 있는 이미지
4. DB 작업 PR인 경우 Table 생성 및 수정 결과에 대해 확인할 수 있는 이미지
1) 판매 입찰 
<img width="1232" alt="bidSell 판매입찰" src="https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/138355289/156e4ffa-e8d3-43c6-a393-81e7fa80e355">
1-1) 판매 -> 입찰 

<img width="991" alt="order 입찰완료" src="https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/138355289/05e5d100-5ab8-454f-8e54-75c4ff09ab4d">

2) 구애 입찰 
<img width="848" alt="BidBuys 구매입찰" src="https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/138355289/717dbe06-e032-41ec-89cb-3e729201d742">

2-1) 구매 -> 입찰
<img width="1035" alt="order 입찰완료 2" src="https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/138355289/a3011747-bfcc-4b53-8dce-f20c40048fc2">

<br />

## :: 기타 질문 및 특이 사항
경매 시스템 구현 자체가 어려워 동작이 가능한지 우선적으로 만들어서 
토큰을 통해 userId 를 가져오는 방법은 피드백 수정 후 작성할 예정입니다.
포인트 사용 여부는 프론트와 작업 속도를 상의 후 추가 여부를 확인 할 것 같습니다.  

코드가 복잡하다보니 약간의 하드코딩을 한 부분이 있고 어떻게 효율적으로 리펙토링 할 수 있을지 조언이 필요합니다.

2023-08-29 03:34 UTC, kyeongraekim requested changes

2023-08-29 03:34 UTC, kyeongraekim commented on src/models/bid.dao.js
> +//Sell module//
- 코드 독해로 의미파악이 충분한 불필요한 주석문을 삭제하여주세요!~

2023-08-29 03:34 UTC, kyeongraekim commented on src/models/bid.dao.js
> +      and status = "구매입찰"
- status는 다음의 내역으로 데이터 관리를 해주세요. 객체지향 프로그램에서 단편적인 정보의 나열을 application level 에서 구사하는 enum 클래스를 최대한 차용한 자바스크립트 에서의 표현법입니다.
- 위치는 models/enums.js 로 설정 해주세요!~


```javascript
const bidStatusEnum = Object.freeze({
     BUY_CONFIRMED : "판매입찰",
     SELL_CONFIRMED : "구매입찰"
     ,... 이하 생략
})

2023-08-29 03:34 UTC, kyeongraekim commented on src/models/bid.dao.js
> +      and status = "구매입찰"
- 위 내용으로 "구매입찰" 하드코딩으로 삽입한 내용을, bidStatusEnum.BUY_CONFIRMED로 접근가능하게 됩니다.

2023-08-29 03:34 UTC, kyeongraekim commented on src/models/bid.dao.js
> +      set status = "입찰완료"
- 해당 내용도 마찬가지입니다/

2023-08-29 03:34 UTC, kyeongraekim commented on src/utils/test.js
> +};
- uuid randomNumber는 uuid4() 메소드를 활용하여 상호간 중복의 가능성을 최소한으로 줄여주세요!

2023-08-29 03:48 UTC, Junjiii commented on src/utils/test.js
> +};
해당 부분은 맨 처음 구상 했을 당시 
<img width="677" alt="스크린샷 2023-08-29 오후 12 43 08" src="https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/138355289/631557e2-131b-4a89-900f-d9dbe5c20fe4">
이런 방식으로 같은 파일 안에서 해당 함수 밖에서 불러오는 방식으로 시도 했었는데 계속 참조에러가 떠서 여러번 시도 해봤지만 해결이 안되어 안으로 넣는 하드코딩을 했었습니다. 말씀하신 방법이 제가 말씀드린 방법으로 중복되지 않게 수정한다는 말씀이신가요??

2023-08-29 03:49 UTC, kyeongraekim requested changes

2023-08-29 03:49 UTC, kyeongraekim commented on src/utils/test.js
> +};
- test라는 파일명이 다수 불분명해보입니다. orderNumberGenerator 정도로 수정해주세요.

2023-08-29 03:49 UTC, kyeongraekim commented on src/services/bid.service.js
> +  };
- 이 곳은 utils 에 정의핸 내용과 같은 기능을 하고 있는 것처럼 보이네요!

2023-08-29 03:49 UTC, kyeongraekim commented on src/services/bid.service.js
> +  }
- 전체 로직을 잘 작성해주셨으나. 경매와 관련된 내용은 DAO단에서 transaction 기능이 필히 삽입되어있어야 합니다.
- 혹시 가능하시다면, DAO로 migration을 하는 방법을 한 번 고민해주세요! 시간 관계상 불가능하시다고 판단된다면 제게 코멘트로 알려주세요!

2023-08-29 03:52 UTC, Junjiii commented on src/services/bid.service.js
> +  };
이 부분은 발견 못하고 실수로 보낸 파일 입니다! 현재는 삭제하고 insertBidSellOrOrder 함수 안에 랜덤 기능 함수를 넣었습니다.

2023-08-29 04:08 UTC, Junjiii commented on src/services/bid.service.js
> +  }
시간 여유있어서 시도해보고 싶은데 혹시 시간 괜찮으실때 강의 한 번 부탁드려도 될까요?? 어려우시다면 찾아서 시도해보겠습니다!

2023-08-30 07:35 UTC, kyeongraekim commented on src/services/bid.service.js
> +  }
https://orkhan.gitbook.io/typeorm/docs/transactions 
위 링크 참고해주세요!~

2023-08-31 06:15 UTC, kyeongraekim approved these changes

2023-08-31 06:15 UTC, merged