구매/판매 각 사이즈별 가격 나타내기
wecode-bootcamp-korea/48-2nd-F_Kiiler-backend pull request #9
Opened 2023-08-28 03:15 UTC by minsu0717

## :: 최근 작업 주제 (하나 이상의 주제를 선택해주세요.)
- [x] 기능 추가
- [ ] 데이터베이스 작업
- [ ] 리팩토링
- [ ] 버그 수정
- [ ] 컨벤션 수정

<br />

## :: 구현 목표 - 해당 브랜치(PR)에서 구현하고자 하는 하나의 목표 작성
-구매/판매 페이지에 각 사이즈별 가격 표시

<br />

## :: 구현 사항 설명 - 해당 브랜치(PR)에서 작업한 내용 작성
- 구매/판매 페이지에 각 사이즈별 가격 표시

<br />

## :: 테스트 결과 이미지
 
![image](https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/96038772/82cb1173-0117-46a7-8dd5-46d8a63bdfd6)
![image](https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/96038772/31c6d41b-2362-41a6-9cca-94abb5bc0e5a)

![image](https://github.com/wecode-bootcamp-korea/48-2nd-F_Kiiler-backend/assets/96038772/14b6d8d7-f0f3-4d28-a284-0d041abb29c3)

<br />

2023-08-28 08:32 UTC, kyeongraekim requested changes

2023-08-28 08:32 UTC, kyeongraekim commented on src/controllers/buy.controller.js
> +});
- 해당 내용은 아래와 같이 삼항 연산자를 써서 조금은 더 깔끔하게 표현이 가능할 것 같습니다!

```javascript
const result = size
  ? await buyDao.getBuySizeList(productId, size)
  : await buyDao.getBuyList(productId);

res.status(201).json({ data: result });

2023-08-28 08:32 UTC, kyeongraekim commented on src/controllers/sell.controller.js
> +});
- 이곳도 위 리뷰 한 번 참고해주세요!~

2023-08-28 08:32 UTC, kyeongraekim commented on src/services/user.service.js
> +    const error = new Error('INVALID_USER');
- 해당 내용 프리티어 설정의 차이로 인해서 팀원들과 쌍따옴표, 따옴표 차이가 생기는 것이라면, 프리티어를 적용하신 분이 팀원분들께 공유해주셔서 모두가 같은 설정 환경에서의 개발을 할 수 있게 도와주세요!

2023-08-28 09:34 UTC, kyeongraekim requested changes

2023-08-28 09:34 UTC, kyeongraekim commented on src/controllers/buy.controller.js
> +    res.status(201).json({ data: result });
- 해당 내용 if-else 분기를 벗어날 수 있는 내용으로 가이드 안내 드렸었는데 이전 리뷰 참고해서 리팩토링에 도전해보세요!

2023-08-29 03:17 UTC, kyeongraekim requested changes

2023-08-29 03:17 UTC, kyeongraekim commented on src/controllers/buy.controller.js
> +  }
- buy 내용에 sell 내용이 포함되어 있어 보이네요!

2023-08-29 03:17 UTC, kyeongraekim commented on src/controllers/buy.controller.js
> +  }
- 혹시 해당 내용의 비즈니스로직 기획을 코멘트로 간단히 남겨주실 수 있으신가요?

2023-08-29 03:46 UTC, minsu0717 commented on src/controllers/buy.controller.js
> +  }
크림에 각 사이즈에 대한 구매나 판매 버튼을 눌렀을때 즉시구매가와 즉시판매가가 나와있어서 저희가 sell과 buy를 테이블을 따로 나눠서 sell에는 buy, buy에는 sell을 result 에 포함시켜줬습니다

2023-08-29 07:07 UTC, kyeongraekim approved these changes

2023-08-29 07:07 UTC, merged